# Generated by Django 5.2.1 on 2025-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='song_id',
            new_name='track_id',
        ),
        migrations.AddField(
            model_name='favourite',
            name='track_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
